server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
management:
  security:
    enabled: false
http:
  mappers:
    jsonPrettyPrint: true
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
