server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
management:
  security:
    enabled: false
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin