server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:TheWalkingPanda/spring-cloud-config.git
  application:
    name: config-server
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  boot:
    admin:
      url: http://localhost:8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
management:
  security:
    enabled: false